// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASM0dQQoqoM19yOYmywF7_IBSYcodqzjk',
    appId: '1:33843014639:web:3fad653129040c5d5ca41a',
    messagingSenderId: '33843014639',
    projectId: 'tridev-library',
    authDomain: 'tridev-library.firebaseapp.com',
    storageBucket: 'tridev-library.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXbQ0hYIzHEBeqMpKe2cKgJuahZkl4e3Y',
    appId: '1:33843014639:android:ee6fbe896655869a5ca41a',
    messagingSenderId: '33843014639',
    projectId: 'tridev-library',
    storageBucket: 'tridev-library.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcm7h21w5tVQ95sAs00LRqAo0Mm3_brpM',
    appId: '1:33843014639:ios:e1be4ea3b79e4a035ca41a',
    messagingSenderId: '33843014639',
    projectId: 'tridev-library',
    storageBucket: 'tridev-library.firebasestorage.app',
    iosBundleId: 'com.example.studyhall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcm7h21w5tVQ95sAs00LRqAo0Mm3_brpM',
    appId: '1:33843014639:ios:e1be4ea3b79e4a035ca41a',
    messagingSenderId: '33843014639',
    projectId: 'tridev-library',
    storageBucket: 'tridev-library.firebasestorage.app',
    iosBundleId: 'com.example.studyhall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASM0dQQoqoM19yOYmywF7_IBSYcodqzjk',
    appId: '1:33843014639:web:66e6ccc76fd128ba5ca41a',
    messagingSenderId: '33843014639',
    projectId: 'tridev-library',
    authDomain: 'tridev-library.firebaseapp.com',
    storageBucket: 'tridev-library.firebasestorage.app',
  );

}